
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "uib_views_binding.h"

#include "uib_home_view_bindings.h"

static uib_databindings_st g_uib_databindings;

static char* str_lower(const char* const str) {
	int i = 0;
	char* strLower = (char*) malloc((strlen(str) + 1) * sizeof(char));
	while (str[i] != '\0') {
		strLower[i] = tolower(str[i]);
		++i;
	}
	strLower[i]='\0';
	return strLower;
}

widget_binding_type get_binding_type(const char * str_binding_type) {
	widget_binding_type binding_type =text;
	char * formatted_binding_type = str_lower(str_binding_type);
	if (!strcmp(formatted_binding_type, "foreach")) {
		binding_type= foreach;
	}
	free(formatted_binding_type);
	return binding_type;
}

void cleanup_databindings() {

	cleanup_home_view_binding();

}

uib_databindings_st* uib_databindings_get_instance() {
	if (!g_uib_databindings._is_init) {
		g_uib_databindings._is_init = true;
		g_uib_databindings.free_all_databindings = &cleanup_databindings;
		g_uib_databindings.get_binding_type = &get_binding_type;
	}
	return &g_uib_databindings;
}

