
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#include "uib_db_manager.h"
#include "uib_datasources.h"
#include "uib_datamodels.h"


static uib_databinding_manager_st g_uib_databinding_manager;
static uib_binding_info** view_bindings = NULL;
static int binding_count;
static uib_view_context* currentViewContext = NULL;

static void extract_binding_info_from_view_context(const uib_view_context* vc) {
	if(!strcmp(vc->view_name, "home_view")) {
		set_home_view_view_context((uib_home_view_view_context*)vc);
		view_bindings = get_home_view_binding_info();
		binding_count = get_home_view_binding_count();
	} else {
	}
}


static void get_widget_handler(uib_binding_info *binding_info,
		widget_handler_st **widget_handler) {
		dlog_print(DLOG_DEBUG, LOG_TAG, "%s - for %d", __func__, binding_info->widgetType);
	switch (binding_info->widgetType) {

	case uib_label:
		*widget_handler = label_widget_handler_get_instance();
		break;

	default:
		break;
	}
}

/**
 * Iterates through all bindings for current view, and performs binding
 */
void perform_databinding(uib_view_context* vc) {
	dlog_print(DLOG_DEBUG, LOG_TAG, "%s - ", __func__);

	currentViewContext = vc;
	//Extract bindingInfo from this view context
	extract_binding_info_from_view_context(vc);

	for (int i = 0; i < binding_count; ++i) {
		if (view_bindings[i] != NULL) {

			if (view_bindings[i]->dataModelContext) {
				widget_handler_st *widget_handler = NULL;

				Databinding_callback binding_cb = NULL;

				get_widget_handler(view_bindings[i], &widget_handler);
				if (widget_handler != NULL) {
					binding_cb = widget_handler->binding_cb;
					if (binding_cb != NULL) {
						binding_cb(view_bindings[i]->widget,
								view_bindings[i]->binding_element_path,
								view_bindings[i]->binding_type,
								view_bindings[i]->dataModelContext->root_element,
								view_bindings[i]->dataModelContext->datasource->ds_content_type);
					}
				}
			}
		}
	}
}


static void refresh_databinding(){
	dlog_print(DLOG_DEBUG,LOG_TAG,"%s - ",__func__);
	perform_databinding(currentViewContext);
}

static void register_refresh_databinding_callback_to_bound_datamodels() {
	uib_datamodels_get_instance()->register_attached_datasource_update_cb(
			&refresh_databinding);
}

static void cleanup_databinding() {
	dlog_print(DLOG_DEBUG,LOG_TAG,"%s - ",__func__);
	uib_databindings_get_instance()->free_all_databindings();
	uib_datamodels_get_instance()->free_all_datamodels();
	uib_datasource_manager_get_instance()->free_all_datasources();
}

uib_databinding_manager_st* uib_databinding_manager_get_instance() {
	if (!g_uib_databinding_manager._is_init) {
		g_uib_databinding_manager._is_init = true;
		register_refresh_databinding_callback_to_bound_datamodels();
		g_uib_databinding_manager.free_all_databinding_resources =
				&cleanup_databinding;
		g_uib_databinding_manager.perform_databinding = &perform_databinding;
	}
	return &g_uib_databinding_manager;
}

