
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#include "uib_datasources.h"
#include "uib_hass_datasource.h"
#include "uib_datasource_handler_remote.h"

static uib_datasource_manager_st g_uib_datasource_manager;

static uib_datasource_interface* get_datasource_interface_for_datasource_type(enum UIB_DATASOURCE_TYPE);

static uib_datasource_instance* get_datasource_instance(const char* datasource_name) {
uib_datasource_instance* datasource_handle = NULL;

	if(!strcmp(datasource_name, "hass")){
		datasource_handle = get_hass_dataSource_handle();
	}else{
	}

	return datasource_handle;
}

static void cleanup_datasource_interfaces(){
	uib_remote_datasource_get_instance()->cleanup_datasource();

}

static void register_datasource_update_cb(void (*callback)()) {
	uib_datasource_interface* datasource_interface = NULL;
	enum UIB_DATASOURCE_TYPE ds_type = static_source;
	for (; ds_type < end_datasource_type_marker; ++ds_type) {
		datasource_interface = get_datasource_interface_for_datasource_type(
				ds_type);
		if (datasource_interface != NULL)
			datasource_interface->register_datasource_update_callback(callback);
	}
}

static uib_datasource_interface* get_datasource_interface_for_datasource_type(enum UIB_DATASOURCE_TYPE ds_type) {
	uib_datasource_interface* datasource_interface = NULL;
	if (ds_type == remote_API) {
		datasource_interface = uib_remote_datasource_get_instance();
	} else {
	}
	return datasource_interface;
}

static void cleanup_datasources() {
	cleanup_hass_datasource();
	cleanup_datasource_interfaces();
}


uib_datasource_manager_st* uib_datasource_manager_get_instance() {
	if (!g_uib_datasource_manager._is_init) {
		g_uib_datasource_manager._is_init = true;
		g_uib_datasource_manager.free_all_datasources = &cleanup_datasources;
		g_uib_datasource_manager.get_datasource_instance = &get_datasource_instance;
		g_uib_datasource_manager.register_datasource_update_cb =
				&register_datasource_update_cb;
		g_uib_datasource_manager.get_datasource_interface_for_datasource_type =
				&get_datasource_interface_for_datasource_type;
	}
	return &g_uib_datasource_manager;
}

