
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#include "uib_datamodels.h"
#include "uib_hass_entity_datamodel.h"

static uib_datamodels_st g_uib_datamodels;

uib_datamodel_context* get_datamodel_context(const char* dataModelName) {
	uib_datamodel_context* datamodel_context = NULL;

	if(!strcmp(dataModelName, "hass_entity")){
		datamodel_context=get_hass_entity_datamodel_context();
	}else{
	}

	return datamodel_context;
}
void cleanup_datamodels() {
	cleanup_hass_entity_datamodel();
}

void register_attached_datasource_update_cb(void (*callback)()) {
	uib_datasource_manager_get_instance()->register_datasource_update_cb(callback);
}

uib_datamodels_st* uib_datamodels_get_instance() {
	if (!g_uib_datamodels._is_init) {
		g_uib_datamodels._is_init = true;
		g_uib_datamodels.free_all_datamodels = &cleanup_datamodels;
		g_uib_datamodels.get_datamodel_context = &get_datamodel_context;
		g_uib_datamodels.register_attached_datasource_update_cb =
			&register_attached_datasource_update_cb;
	}
	return &g_uib_datamodels;
}
		
		