
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#include "uib_hass_datasource.h"
#include "uib_datasource_handler_remote.h"

static uib_datasource_instance* hass_datasource;

static remote_ds_s* ds;

static void prepare_datasource() {

	//Begin remote datasource definition
	ds = (remote_ds_s *)malloc(sizeof(remote_ds_s));
	char* url = "http://192.168.4.190:8123/api/states?" ;
	strcpy(ds->url, url);//curl_easy_escape(ds->curl,url,strlen(url))
	ds->response_data = (char*)malloc(1*sizeof(char));
	strcpy(ds->response_data,"");
	ds->prev_response_data = (char*)malloc(1*sizeof(char));
	strcpy(ds->prev_response_data,"");
	ds->polling_interval = 5000; //in ms
	ds->timeout_ms = 5000L; //in ms
	ds->source_name = "hass";
	ds->thread_running = false;
	ds->content_type = UIB_JSON;
	eina_lock_new(&ds->mutex);

	set_remote_datasource(ds);

	hass_datasource = (uib_datasource_instance*) malloc(sizeof(uib_datasource_instance));
	hass_datasource->datasource_interface = uib_datasource_manager_get_instance()->get_datasource_interface_for_datasource_type(remote_API);
	hass_datasource->name = "hass";
	hass_datasource->ds_content_type = UIB_JSON;
	hass_datasource->root_element = hass_datasource->datasource_interface->get_datasource_root_element();
}

uib_datasource_instance* get_hass_dataSource_handle() {
	if (hass_datasource == NULL) {
		prepare_datasource();
	}
	return hass_datasource;
}

void cleanup_hass_datasource() {
	free(hass_datasource->root_element[0]);
	hass_datasource->root_element[0] = NULL;
	free(hass_datasource);
	eina_lock_free(&ds->mutex);
	free(ds);
}
