
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void connection_home_view_btn_next_onclicked(uib_home_view_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_home_view_create(Evas_Object* parent, void* create_callback_param) {
	uib_home_view_view_context* vc = calloc(1, sizeof(uib_home_view_view_context));
	vc->parent = parent;
	vc->view_name = "home_view";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->btn_next, "clicked", (Evas_Smart_Cb)connection_home_view_btn_next_onclicked, vc);



	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_home_view_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_home_view_view_context* vc = (uib_home_view_view_context*)uib_app_manager->find_view_context("home_view");
	if(!vc) {
		return;
	}
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->entities) {
			vc->entities= elm_genlist_add(vc->grid1);
		}
		if (!vc->circle_object_entities) {
			vc->circle_object_entities= eext_circle_object_genlist_add(vc->entities, uib_views_get_instance()->get_window_obj()->circle_surface);
			eext_rotary_object_event_activated_set(vc->circle_object_entities, EINA_TRUE);
		}
		if(vc->entities) {
			evas_object_size_hint_align_set(vc->entities, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->entities, 1.0, 1.0);			evas_object_show(vc->entities);
		}
		if (!vc->btn_next) {
			vc->btn_next = elm_button_add(vc->grid1);
		}
		if (vc->btn_next) {
			evas_object_size_hint_align_set(vc->btn_next, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->btn_next, 1.0, 1.0);			elm_object_text_set(vc->btn_next,_UIB_LOCALE("Next"));
			elm_object_style_set(vc->btn_next,"bottom");
			evas_object_show(vc->btn_next);
		}
		if (!vc->hass_box) {
			vc->hass_box = elm_box_add(vc->grid1);
		}
		if(vc->hass_box) {
			elm_win_alpha_set(vc->hass_box, EINA_FALSE);
			elm_box_homogeneous_set(vc->hass_box, EINA_FALSE);
			elm_box_horizontal_set(vc->hass_box, EINA_FALSE);
			elm_box_padding_set(vc->hass_box,0,0);
			evas_object_size_hint_align_set(vc->hass_box, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->hass_box, 1.0, 1.0);
			if (!vc->friendly_name) {
				vc->friendly_name = elm_label_add(vc->hass_box);
			}
			if(vc->friendly_name) {
				evas_object_size_hint_align_set(vc->friendly_name, 0.5, 0.5);				evas_object_size_hint_weight_set(vc->friendly_name, 1.0, 1.0);				elm_object_text_set(vc->friendly_name,_UIB_LOCALE("FriendlyName"));
				elm_label_line_wrap_set(vc->friendly_name, (Elm_Wrap_Type)ELM_WRAP_NONE);
				elm_label_wrap_width_set(vc->friendly_name,0);
				elm_label_ellipsis_set(vc->friendly_name, EINA_FALSE);
				evas_object_show(vc->friendly_name);
			}
			elm_box_pack_end(vc->hass_box, vc->friendly_name);
			evas_object_show(vc->hass_box);
		}
		elm_grid_pack(vc->grid1, vc->entities, 0, 6, 1000, 994);		elm_grid_pack(vc->grid1, vc->btn_next, 100, 850, 800, 80);		elm_grid_pack(vc->grid1, vc->hass_box, 14, 242, 1000, 436);		evas_object_show(vc->grid1);
	}
}

