/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "Eina.h"
#include "uib_hass_entity_datamodel.h"

typedef struct _uib_home_view_control_context {
	/* add your variables here */

} uib_home_view_control_context;

/**
 * @brief the user clicked the button (press/release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */

void home_view_btn_next_onclicked(uib_home_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked at the start of wrapper function home_view_connection_home_view_btn_next_onclicked

}

void home_view_btn_next_onclicked_post(void* param, uib_home_view_view_context *vc, Evas_Object *obj, void *event_info) {
	//Invoked post wrapper function home_view_connection_home_view_btn_next_onclicked

}

void home_view_onuib_view_create(uib_home_view_view_context *vc, Evas_Object *obj, void *event_info) {
	uib_datamodel_context* datamodel = uib_datamodels_get_instance()->get_datamodel_context("hass_entity");

	char *label = "Item X";

	create_genlist_item(vc->entities, "title" , label, _UIB_LOCALE("Sub Text 2"), "","", "","", NULL, ELM_GENLIST_ITEM_NONE, NULL, NULL);
}

