
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef MANAGED_INC_UIB_HOME_VIEW_BINDINGS_H_
#define MANAGED_INC_UIB_HOME_VIEW_BINDINGS_H_


#include "uib_views_binding.h"
#include "uib_databinding_common.h"

#include "uib_home_view_view.h"

uib_binding_info** get_home_view_binding_info();

int get_home_view_binding_count();
void set_home_view_view_context(uib_home_view_view_context* arg_view_context);
void cleanup_home_view_binding();

#endif

