
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef MANAGED_INC_DATABINDING_UIB_HASS_DATASOURCE_H_
#define MANAGED_INC_DATABINDING_UIB_HASS_DATASOURCE_H_
#include "uib_datasources.h"
uib_datasource_instance* get_hass_dataSource_handle();
void cleanup_hass_datasource();
#endif
