
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef MANAGED_INC_UIB_DB_MANAGER_H_
#define MANAGED_INC_UIB_DB_MANAGER_H_
#include <string.h>
#include "uib_views_binding.h"
#include "uib_databinding_common.h"
#include "databinding/uib_widget_handler_hoverselitem.h"
#include "databinding/uib_widget_handler_hoversel.h"
#include "databinding/uib_widget_handler_button.h"
#include "databinding/uib_widget_handler_checkbox.h"
#include "databinding/uib_widget_handler_label.h"
#include "databinding/uib_widget_handler_list.h"
#include "databinding/uib_widget_handler_listitem.h"
#include "databinding/uib_widget_handler_radio.h"
#include "uib_views.h"
#include "databinding/uib_widget_handler_label.h"
#include "uib_home_view_bindings.h"

typedef struct {
	bool _is_init;
	void (*perform_databinding)(uib_view_context* );
	void (*free_all_databinding_resources)();
} uib_databinding_manager_st;

uib_databinding_manager_st* uib_databinding_manager_get_instance();
#endif

