
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/


#ifndef MANAGED_INC_DATABINDING_UIB_VIEWS_BINDING_H_
#define MANAGED_INC_DATABINDING_UIB_VIEWS_BINDING_H_
#include "uib_datamodels.h"
#include "g_inc_uib.h"
#include <ctype.h>

typedef struct {

	Evas_Object* widget;
	char* widgetPropertyId;
	widget_type widgetType;
	//Dot-separated path to bound element in data model
	char* binding_element_path;
	widget_binding_type binding_type;
	uib_datamodel_context* dataModelContext;

} uib_binding_info;

typedef struct {
	bool _is_init;
	widget_binding_type (*get_binding_type)(const char* );
	void (*free_all_databindings)();
} uib_databindings_st;

uib_databindings_st* uib_databindings_get_instance();
#endif 

