
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef MANAGED_INC_DATABINDING_UIB_WIDGET_HANDLER_LABEL_H_
#define MANAGED_INC_DATABINDING_UIB_WIDGET_HANDLER_LABEL_H_

#include "uib_databinding_common.h"
#include <elm_object.h>

widget_handler_st* label_widget_handler_get_instance();

#endif
