
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef MANAGED_INC_DATABINDING_UIB_HASS_ENTITY_DATAMODEL_H_
#define MANAGED_INC_DATABINDING_UIB_HASS_ENTITY_DATAMODEL_H_

#include "uib_datamodels.h"
#include "uib_datasources.h"

uib_datamodel_context* get_hass_entity_datamodel_context();
void cleanup_hass_entity_datamodel();


#endif

