
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#include "uib_home_view_bindings.h"
static uib_binding_info** home_view_bindings = NULL;
static int home_view_binding_count;
uib_home_view_view_context* home_view_context;

static uib_binding_info** add_binding_info() { 

	uib_binding_info** bi = NULL;

	int count = 0;
	home_view_binding_count = 1;
	bi = (uib_binding_info**) malloc(sizeof(uib_binding_info*) * home_view_binding_count);

	uib_datamodel_context* datamodel_context_binding_info1 = uib_datamodels_get_instance()->get_datamodel_context("hass_entity");
	uib_binding_info* binding_info1 = (uib_binding_info *) malloc( sizeof(uib_binding_info));
	binding_info1->widget = home_view_context->friendly_name;
	binding_info1->binding_type = uib_databindings_get_instance()->get_binding_type("text");
	binding_info1->dataModelContext = datamodel_context_binding_info1;
	binding_info1->binding_element_path = "/root/TreeRoot[state='off']/entity_id";
	binding_info1->widgetType = uib_label;
	bi[count++] = binding_info1;

	return bi; 
}

uib_binding_info** get_home_view_binding_info() {
	if (home_view_bindings == NULL) {
		home_view_bindings = add_binding_info();
	}
	return home_view_bindings;
}

int get_home_view_binding_count(){
	return home_view_binding_count;
}
static void update_view_context_refs() {
	if (home_view_bindings == NULL) {
		home_view_bindings = add_binding_info();
	} else {
		int count = 0;
		home_view_bindings[count++]->widget = home_view_context->friendly_name;
	}
}
void set_home_view_view_context(uib_home_view_view_context* arg_view_context){
	home_view_context = arg_view_context;
	update_view_context_refs();
}
void cleanup_home_view_binding() {
	for (int i = 0; i < home_view_binding_count; ++i) {
		free(home_view_bindings[i]);
	}
	free(home_view_bindings);
	home_view_bindings = NULL;
}
