
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and every time you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "app_main.h"
#include "uib_views_inc.h"

void connection_home_view_btn_next_onclicked(uib_home_view_view_context *vc, Evas_Object *obj, void *event_info){
	home_view_btn_next_onclicked(vc, obj, event_info);
	Elm_Object_Item* navi_item = uib_util_push_view("view2");
	home_view_btn_next_onclicked_post(navi_item, vc, obj, event_info);
}
